# Generated by Django 2.2.2 on 2020-02-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_type', models.IntegerField()),
                ('Task_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Update_type', models.CharField(choices=[('perday', 'per day'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Task')),
            ],
        ),
    ]
